// Auto-generated by VibeStack — do not edit manually
import { Link, Outlet } from "@tanstack/react-router";

const navLinks = [
	{ to: "/bookmark", label: "Bookmarks" },
	{ to: "/tag", label: "Tags" },
	{ to: "/bookmark-tag", label: "Bookmark Tags" },
];

export function AppLayout() {
	return (
		<div className="min-h-screen bg-background">
			<header className="border-b">
				<nav className="container mx-auto flex items-center gap-6 py-4">
					<Link to="/" className="text-lg font-bold">
						MarkNest
					</Link>
					{navLinks.map((link) => (
						<Link
							key={link.to}
							to={link.to}
							className="text-sm text-muted-foreground hover:text-foreground"
							activeProps={{ className: "text-foreground font-medium" }}
						>
							{link.label}
						</Link>
					))}
				</nav>
			</header>
			<main className="container mx-auto py-6">
				<Outlet />
			</main>
		</div>
	);
}
